global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "terranote-core"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "terranote-core:8000"

